# --- Build Stage ---
FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

# 设置国内代理，加速依赖下载
ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.cn,direct

RUN go mod download

COPY . .

# 【关键区别】编译的是 consumer 的 main.go 文件
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /app/consumer ./cmd/consumer

# --- Final Stage ---
FROM alpine:latest

# 从构建阶段拷贝编译好的二进制文件
COPY --from=builder /app/consumer /consumer

# 添加CA证书，以便程序可以发起HTTPS请求等
RUN apk --no-cache add ca-certificates tzdata
# RUN apk --no-cache add ca-certificates
# 指定使用上海时区
ENV TZ=Asia/Shanghai

# 容器启动时执行的命令
ENTRYPOINT ["/consumer"]