# Promtail自身的服务配置
server:
  # Promtail也会暴露一个HTTP端口，主要用于Prometheus抓取它自身的健康状况指标，以及提供调试API
  http_listen_port: 9080
  # 禁用gRPC端口（设置为0）
  grpc_listen_port: 0

positions:
  # 这是Promtail的“书签”文件。它会记录每个日志文件读取到了哪一行。这样，即使Promtail重启，也能从上次的位置继续读取，避免重复发送日志
  filename: /tmp/positions.yaml

# 客户端配置，即日志要发送到的目标
clients:
  # 告诉Promtail，所有收集到的日志都要推送到Loki的API端点
  - url: http://loki:3100/loki/api/v1/push

# 抓取配置列表，告诉Promtail去哪里找日志
scrape_configs:
  # 一个名为"system"的job。
  - job_name: system
    # 手动定义日志源
    static_configs:
      # 目标是Promtail容器自身
      - targets:
          - localhost
        # 为从这个job抓取的所有日志附加固定的标签
        labels:
          job: varlogs
          # 告诉Promtail去监视`/var/log/`目录下所有以`.log`结尾的文件
          __path__: /var/log/*log

  # 一个名为"containers"的job，这是实现自动发现的关键
  - job_name: containers
    # 使用"Docker Service Discovery"（Docker服务发现）
    docker_sd_configs:
      # 告诉Promtail通过Docker的socket文件与Docker守护进程通信，以获取所有容器的信息
      - host: unix:///var/run/docker.sock
        # 每5秒向Docker查询一次容器列表的更新
        refresh_interval: 5s
    # 重新打标签的配置。这是将Docker提供的信息转化为Loki标签的魔法所在
    relabel_configs:
      # 源标签：使用Docker服务发现提供的容器名元数据（例如, '/api-server'）
      - source_labels: ['__meta_docker_container_name']
        # 正则表达式：匹配并捕获容器名中'/'之后的所有内容
        regex: '/(.*)'
        # 目标标签：将捕获到的内容（例如, 'api-server'）赋值给一个新的Loki标签，名为'container'
        target_label: 'container'
      # 源标签：使用日志流的类型（'stdout'或'stderr'）
      - source_labels: ['__meta_docker_container_log_stream']
        # 目标标签：创建一个名为'logstream'的Loki标签
        target_label: 'logstream'